### ISSUE TITLE
Inconsistency in compass handout

### ISSUE THREAD

**Issue by Restioson** [NucleoidMC/Game-Gui#1]
Sometimes you get a compass, sometimes you don't. Maybe it could give you one whenever you spawn in the hub if you do not already have one?

**Comment by thecatcore** [comment]
For now it gives the player the compass when they join the server and don't have it in their inventory.

**Comment by Restioson** [comment]
As of last playtest this wasn't working. Has it been updated since them?

**Comment by thecatcore** [comment]
We’ll see during next playtest

**Comment by Restioson** [comment]
I didn't receive a compass during the last one. I'm not sure whether the plugin was installed on the server though.

**Comment by Restioson** [comment]
Works now
